from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(390, 640)
        Form.setMinimumSize(QtCore.QSize(390, 640))
        Form.setMaximumSize(QtCore.QSize(390, 640))
        self.welcome_label = QtWidgets.QLabel(parent=Form)
        self.welcome_label.setEnabled(True)
        self.welcome_label.setGeometry(QtCore.QRect(20, 100, 351, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome_label.sizePolicy().hasHeightForWidth())
        self.welcome_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.welcome_label.setFont(font)
        self.welcome_label.setMouseTracking(True)
        self.welcome_label.setTabletTracking(False)
        self.welcome_label.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.welcome_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.welcome_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.welcome_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.welcome_label.setScaledContents(False)
        self.welcome_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.welcome_label.setWordWrap(False)
        self.welcome_label.setOpenExternalLinks(False)
        self.welcome_label.setObjectName("welcome_label")
        self.welcome_label_2 = QtWidgets.QLabel(parent=Form)
        self.welcome_label_2.setGeometry(QtCore.QRect(20, 140, 351, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome_label_2.sizePolicy().hasHeightForWidth())
        self.welcome_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.welcome_label_2.setFont(font)
        self.welcome_label_2.setMouseTracking(True)
        self.welcome_label_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.welcome_label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.welcome_label_2.setStyleSheet("color:rgb(156, 36, 0)")
        self.welcome_label_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.welcome_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.welcome_label_2.setObjectName("welcome_label_2")
        self.layoutWidget = QtWidgets.QWidget(parent=Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 210, 351, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_label = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.login_label.setFont(font)
        self.login_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.login_label.setObjectName("login_label")
        self.verticalLayout.addWidget(self.login_label)
        self.login_edit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.login_edit.setFont(font)
        self.login_edit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.login_edit.setStyleSheet("QLineEdit {     border-radius: 8px; background-color: rgb(255, 255, 255);\n"
"padding: 0px 6px;\n"
" color:rgb(156, 36, 0) }")
        self.login_edit.setMaxLength(12)
        self.login_edit.setObjectName("login_edit")
        self.verticalLayout.addWidget(self.login_edit)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pass_label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.pass_label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pass_label.setFont(font)
        self.pass_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.pass_label.setObjectName("pass_label")
        self.verticalLayout_3.addWidget(self.pass_label)
        self.pass_edit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.pass_edit.setFont(font)
        self.pass_edit.setStyleSheet("QLineEdit {     border-radius: 8px; background-color: rgb(255, 255, 255);\n"
"padding: 0px 6px;\n"
" color:rgb(156, 36, 0) }")
        self.pass_edit.setMaxLength(12)
        self.pass_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.pass_edit.setObjectName("pass_edit")
        self.verticalLayout_3.addWidget(self.pass_edit)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.btn = QtWidgets.QVBoxLayout()
        self.btn.setContentsMargins(70, 50, 70, -1)
        self.btn.setSpacing(21)
        self.btn.setObjectName("btn")
        self.sign_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.sign_btn.setFont(font)
        self.sign_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.sign_btn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.sign_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 92, 71);\n"
"    color:  rgb(255, 255, 255);\n"
"    font-size:  25px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 162, 125);\n"
"}")
        self.sign_btn.setObjectName("sign_btn")
        self.btn.addWidget(self.sign_btn)
        self.regist_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.regist_btn.setFont(font)
        self.regist_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.regist_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color:  rgb(255, 92, 71);\n"
"    color:  rgb(255, 255, 255);\n"
"    font-size:  25px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 162, 125);\n"
"}")
        self.regist_btn.setObjectName("regist_btn")
        self.btn.addWidget(self.regist_btn)
        self.verticalLayout_2.addLayout(self.btn)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(-10, -10, 401, 671))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("photo_2024-05-19_01-22-38.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.welcome_label.raise_()
        self.welcome_label_2.raise_()
        self.layoutWidget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Онлайн школа Бебрика - авторизация"))
        self.welcome_label.setText(_translate("Form", "Добро пожаловать"))
        self.welcome_label_2.setText(_translate("Form", "в онлайн школу Бебрика!"))
        self.login_label.setText(_translate("Form", "Логин:"))
        self.pass_label.setText(_translate("Form", "Пароль:"))
        self.sign_btn.setText(_translate("Form", "Войти"))
        self.regist_btn.setText(_translate("Form", "Регистрация"))
