# Form implementation generated from reading ui file 'MainWindowStudent.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindowStudent(object):
    def setupUi(self, MainWindowStudent):
        MainWindowStudent.setObjectName("MainWindowStudent")
        MainWindowStudent.resize(1134, 625)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindowStudent)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, 0, 301, 631))
        self.widget.setStyleSheet("QWidget { \n"
"    background:  rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton {\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background: rgb(255, 85, 127);\n"
"}")
        self.widget.setObjectName("widget")
        self.my_account_btn = QtWidgets.QPushButton(parent=self.widget)
        self.my_account_btn.setGeometry(QtCore.QRect(40, 170, 211, 28))
        self.my_account_btn.setStyleSheet("QWidget { \n"
"    background:  rgb(255, 170, 127); \n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 92, 71);\n"
"    color:  rgb(255, 255, 255);\n"
"    font-size:  25px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background: rgb(255, 162, 125);\n"
"}")
        self.my_account_btn.setCheckable(True)
        self.my_account_btn.setChecked(True)
        self.my_account_btn.setAutoExclusive(True)
        self.my_account_btn.setObjectName("my_account_btn")
        self.schedule_btn = QtWidgets.QPushButton(parent=self.widget)
        self.schedule_btn.setGeometry(QtCore.QRect(40, 240, 211, 28))
        self.schedule_btn.setStyleSheet("QWidget { \n"
"    background:  rgb(255, 170, 127); \n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 92, 71);\n"
"    color:  rgb(255, 255, 255);\n"
"    font-size:  25px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background: rgb(255, 162, 125);\n"
"}")
        self.schedule_btn.setCheckable(True)
        self.schedule_btn.setAutoExclusive(True)
        self.schedule_btn.setObjectName("schedule_btn")
        self.teachers_btn = QtWidgets.QPushButton(parent=self.widget)
        self.teachers_btn.setGeometry(QtCore.QRect(40, 310, 211, 28))
        self.teachers_btn.setStyleSheet("QWidget { \n"
"    background:  rgb(255, 170, 127); \n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 92, 71);\n"
"    color:  rgb(255, 255, 255);\n"
"    font-size:  25px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background: rgb(255, 162, 125);\n"
"}\n"
"")
        self.teachers_btn.setCheckable(True)
        self.teachers_btn.setAutoExclusive(True)
        self.teachers_btn.setObjectName("teachers_btn")
        self.logo = QtWidgets.QLabel(parent=self.widget)
        self.logo.setGeometry(QtCore.QRect(100, 10, 91, 111))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("photo_2024-05-17_15-45-57.jpg"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.lesson_btn = QtWidgets.QPushButton(parent=self.widget)
        self.lesson_btn.setGeometry(QtCore.QRect(40, 380, 211, 28))
        self.lesson_btn.setStyleSheet("QWidget { \n"
"    background:  rgb(255, 170, 127); \n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 92, 71);\n"
"    color:  rgb(255, 255, 255);\n"
"    font-size:  25px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background: rgb(255, 162, 125);\n"
"}\n"
"")
        self.lesson_btn.setCheckable(True)
        self.lesson_btn.setAutoExclusive(True)
        self.lesson_btn.setObjectName("lesson_btn")
        self.exit_btn = QtWidgets.QPushButton(parent=self.widget)
        self.exit_btn.setGeometry(QtCore.QRect(40, 550, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.exit_btn.setFont(font)
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.exit_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color:  rgb(255, 92, 71);\n"
"    color:  rgb(255, 255, 255);\n"
"    font-size:  25px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 162, 125);\n"
"}")
        self.exit_btn.setObjectName("exit_btn")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(299, -1, 841, 631))
        self.widget_2.setStyleSheet("QWidget { \n"
"    background: rgb(255, 212, 194); \n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_2)
        self.stackedWidget.setGeometry(QtCore.QRect(39, 39, 761, 551))
        self.stackedWidget.setObjectName("stackedWidget")
        self.my_account_page = QtWidgets.QWidget()
        self.my_account_page.setObjectName("my_account_page")
        self.name_label = QtWidgets.QLabel(parent=self.my_account_page)
        self.name_label.setGeometry(QtCore.QRect(20, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.name_label.setObjectName("name_label")
        self.name_edit = QtWidgets.QLineEdit(parent=self.my_account_page)
        self.name_edit.setGeometry(QtCore.QRect(150, 39, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name_edit.setFont(font)
        self.name_edit.setStyleSheet("QLineEdit {     \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.name_edit.setMaxLength(16)
        self.name_edit.setObjectName("name_edit")
        self.surname_edit = QtWidgets.QLineEdit(parent=self.my_account_page)
        self.surname_edit.setGeometry(QtCore.QRect(150, 110, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.surname_edit.setFont(font)
        self.surname_edit.setStyleSheet("QLineEdit {     \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.surname_edit.setMaxLength(16)
        self.surname_edit.setObjectName("surname_edit")
        self.surname_label = QtWidgets.QLabel(parent=self.my_account_page)
        self.surname_label.setGeometry(QtCore.QRect(20, 111, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.surname_label.setFont(font)
        self.surname_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.surname_label.setObjectName("surname_label")
        self.class_edit = QtWidgets.QLineEdit(parent=self.my_account_page)
        self.class_edit.setGeometry(QtCore.QRect(150, 180, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.class_edit.setFont(font)
        self.class_edit.setStyleSheet("QLineEdit {     \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.class_edit.setMaxLength(16)
        self.class_edit.setObjectName("class_edit")
        self.class_label = QtWidgets.QLabel(parent=self.my_account_page)
        self.class_label.setGeometry(QtCore.QRect(20, 180, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.class_label.setFont(font)
        self.class_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.class_label.setObjectName("class_label")
        self.item_comboBox = QtWidgets.QComboBox(parent=self.my_account_page)
        self.item_comboBox.setGeometry(QtCore.QRect(150, 251, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.item_comboBox.setFont(font)
        self.item_comboBox.setStyleSheet("QComboBox {    \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.item_comboBox.setObjectName("item_comboBox")
        self.item_comboBox.addItem("")
        self.item_comboBox.addItem("")
        self.item_comboBox.addItem("")
        self.item_comboBox.addItem("")
        self.item_comboBox.addItem("")
        self.item_comboBox.addItem("")
        self.item_comboBox.addItem("")
        self.item_label = QtWidgets.QLabel(parent=self.my_account_page)
        self.item_label.setGeometry(QtCore.QRect(20, 250, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.item_label.setFont(font)
        self.item_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.item_label.setObjectName("item_label")
        self.redpass_label = QtWidgets.QLabel(parent=self.my_account_page)
        self.redpass_label.setGeometry(QtCore.QRect(20, 370, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.redpass_label.setFont(font)
        self.redpass_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.redpass_label.setObjectName("redpass_label")
        self.oldpass_edit = QtWidgets.QLineEdit(parent=self.my_account_page)
        self.oldpass_edit.setGeometry(QtCore.QRect(240, 430, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oldpass_edit.setFont(font)
        self.oldpass_edit.setStyleSheet("QLineEdit {     \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.oldpass_edit.setText("")
        self.oldpass_edit.setMaxLength(16)
        self.oldpass_edit.setObjectName("oldpass_edit")
        self.newpass_edit = QtWidgets.QLineEdit(parent=self.my_account_page)
        self.newpass_edit.setGeometry(QtCore.QRect(240, 480, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.newpass_edit.setFont(font)
        self.newpass_edit.setStyleSheet("QLineEdit {     \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.newpass_edit.setMaxLength(16)
        self.newpass_edit.setObjectName("newpass_edit")
        self.oldpass_label = QtWidgets.QLabel(parent=self.my_account_page)
        self.oldpass_label.setGeometry(QtCore.QRect(20, 430, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.oldpass_label.setFont(font)
        self.oldpass_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.oldpass_label.setObjectName("oldpass_label")
        self.newpass_label = QtWidgets.QLabel(parent=self.my_account_page)
        self.newpass_label.setGeometry(QtCore.QRect(20, 480, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.newpass_label.setFont(font)
        self.newpass_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.newpass_label.setObjectName("newpass_label")
        self.photo_label = QtWidgets.QLabel(parent=self.my_account_page)
        self.photo_label.setGeometry(QtCore.QRect(480, 40, 231, 241))
        font = QtGui.QFont()
        font.setItalic(False)
        self.photo_label.setFont(font)
        self.photo_label.setTabletTracking(False)
        self.photo_label.setStyleSheet("QLabel {\n"
"    border-radius: 50%;\n"
"    background-size: cover;\n"
"}\n"
"")
        self.photo_label.setText("")
        self.photo_label.setPixmap(QtGui.QPixmap("human_icon.png"))
        self.photo_label.setScaledContents(True)
        self.photo_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.photo_label.setWordWrap(False)
        self.photo_label.setIndent(-1)
        self.photo_label.setOpenExternalLinks(False)
        self.photo_label.setObjectName("photo_label")
        self.create_btn = QtWidgets.QPushButton(parent=self.my_account_page)
        self.create_btn.setGeometry(QtCore.QRect(490, 370, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.create_btn.setFont(font)
        self.create_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color:  rgb(255, 92, 71);\n"
"    color:  rgb(255, 255, 255);\n"
"    font-size:  25px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 162, 125);\n"
"}")
        self.create_btn.setObjectName("create_btn")
        self.save_btn = QtWidgets.QPushButton(parent=self.my_account_page)
        self.save_btn.setGeometry(QtCore.QRect(490, 430, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.save_btn.setFont(font)
        self.save_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color:  rgb(255, 92, 71);\n"
"    color:  rgb(255, 255, 255);\n"
"    font-size:  25px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 162, 125);\n"
"}")
        self.save_btn.setObjectName("save_btn")
        self.stackedWidget.addWidget(self.my_account_page)
        self.chat_page = QtWidgets.QWidget()
        self.chat_page.setObjectName("chat_page")
        self.widget_5 = QtWidgets.QWidget(parent=self.chat_page)
        self.widget_5.setGeometry(QtCore.QRect(10, 480, 741, 51))
        self.widget_5.setStyleSheet("QWidget { \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton.setGeometry(QtCore.QRect(700, 10, 31, 31))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("photo_2024-05-17_15-45-57.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.chat_page)
        self.schedule_page = QtWidgets.QWidget()
        self.schedule_page.setObjectName("schedule_page")
        self.sun_edit = QtWidgets.QLineEdit(parent=self.schedule_page)
        self.sun_edit.setGeometry(QtCore.QRect(560, 60, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sun_edit.setFont(font)
        self.sun_edit.setStyleSheet("QLineEdit {     \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.sun_edit.setMaxLength(16)
        self.sun_edit.setObjectName("sun_edit")
        self.thu_label = QtWidgets.QLabel(parent=self.schedule_page)
        self.thu_label.setGeometry(QtCore.QRect(290, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.thu_label.setFont(font)
        self.thu_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.thu_label.setObjectName("thu_label")
        self.update_btn = QtWidgets.QPushButton(parent=self.schedule_page)
        self.update_btn.setGeometry(QtCore.QRect(560, 250, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.update_btn.setFont(font)
        self.update_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.update_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color:  rgb(255, 92, 71);\n"
"    color:  rgb(255, 255, 255);\n"
"    font-size:  25px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 162, 125);\n"
"}")
        self.update_btn.setObjectName("update_btn")
        self.mon_edit = QtWidgets.QLineEdit(parent=self.schedule_page)
        self.mon_edit.setGeometry(QtCore.QRect(20, 60, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.mon_edit.setFont(font)
        self.mon_edit.setStyleSheet("QLineEdit {     \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.mon_edit.setMaxLength(16)
        self.mon_edit.setObjectName("mon_edit")
        self.fri_edit = QtWidgets.QLineEdit(parent=self.schedule_page)
        self.fri_edit.setGeometry(QtCore.QRect(290, 250, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fri_edit.setFont(font)
        self.fri_edit.setStyleSheet("QLineEdit {     \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.fri_edit.setMaxLength(16)
        self.fri_edit.setObjectName("fri_edit")
        self.sun_label = QtWidgets.QLabel(parent=self.schedule_page)
        self.sun_label.setGeometry(QtCore.QRect(560, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.sun_label.setFont(font)
        self.sun_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.sun_label.setObjectName("sun_label")
        self.tue_edit = QtWidgets.QLineEdit(parent=self.schedule_page)
        self.tue_edit.setGeometry(QtCore.QRect(20, 250, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tue_edit.setFont(font)
        self.tue_edit.setStyleSheet("QLineEdit {     \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.tue_edit.setMaxLength(16)
        self.tue_edit.setObjectName("tue_edit")
        self.thu_edit = QtWidgets.QLineEdit(parent=self.schedule_page)
        self.thu_edit.setGeometry(QtCore.QRect(290, 60, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.thu_edit.setFont(font)
        self.thu_edit.setStyleSheet("QLineEdit {     \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.thu_edit.setMaxLength(16)
        self.thu_edit.setObjectName("thu_edit")
        self.tue_label = QtWidgets.QLabel(parent=self.schedule_page)
        self.tue_label.setGeometry(QtCore.QRect(20, 210, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.tue_label.setFont(font)
        self.tue_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.tue_label.setObjectName("tue_label")
        self.fri_label = QtWidgets.QLabel(parent=self.schedule_page)
        self.fri_label.setGeometry(QtCore.QRect(290, 210, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.fri_label.setFont(font)
        self.fri_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.fri_label.setObjectName("fri_label")
        self.mon_label = QtWidgets.QLabel(parent=self.schedule_page)
        self.mon_label.setGeometry(QtCore.QRect(20, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.mon_label.setFont(font)
        self.mon_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.mon_label.setObjectName("mon_label")
        self.sat_label = QtWidgets.QLabel(parent=self.schedule_page)
        self.sat_label.setGeometry(QtCore.QRect(290, 400, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.sat_label.setFont(font)
        self.sat_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.sat_label.setObjectName("sat_label")
        self.sat_edit = QtWidgets.QLineEdit(parent=self.schedule_page)
        self.sat_edit.setGeometry(QtCore.QRect(290, 440, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sat_edit.setFont(font)
        self.sat_edit.setStyleSheet("QLineEdit {     \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.sat_edit.setMaxLength(16)
        self.sat_edit.setObjectName("sat_edit")
        self.wed_label = QtWidgets.QLabel(parent=self.schedule_page)
        self.wed_label.setGeometry(QtCore.QRect(20, 400, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.wed_label.setFont(font)
        self.wed_label.setStyleSheet("color:rgb(156, 36, 0)")
        self.wed_label.setObjectName("wed_label")
        self.wed_edit = QtWidgets.QLineEdit(parent=self.schedule_page)
        self.wed_edit.setGeometry(QtCore.QRect(20, 440, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.wed_edit.setFont(font)
        self.wed_edit.setStyleSheet("QLineEdit {     \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.wed_edit.setMaxLength(16)
        self.wed_edit.setObjectName("wed_edit")
        self.stackedWidget.addWidget(self.schedule_page)
        self.teachers_page = QtWidgets.QWidget()
        self.teachers_page.setObjectName("teachers_page")
        self.widget_3 = QtWidgets.QWidget(parent=self.teachers_page)
        self.widget_3.setGeometry(QtCore.QRect(140, 110, 501, 191))
        self.widget_3.setStyleSheet("QWidget { \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.class_label_4 = QtWidgets.QLabel(parent=self.widget_3)
        self.class_label_4.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.class_label_4.setFont(font)
        self.class_label_4.setStyleSheet("color:rgb(156, 36, 0)")
        self.class_label_4.setObjectName("class_label_4")
        self.class_label_5 = QtWidgets.QLabel(parent=self.widget_3)
        self.class_label_5.setGeometry(QtCore.QRect(10, 70, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.class_label_5.setFont(font)
        self.class_label_5.setStyleSheet("color:rgb(156, 36, 0)")
        self.class_label_5.setObjectName("class_label_5")
        self.class_label_6 = QtWidgets.QLabel(parent=self.widget_3)
        self.class_label_6.setGeometry(QtCore.QRect(10, 130, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.class_label_6.setFont(font)
        self.class_label_6.setStyleSheet("color:rgb(156, 36, 0)")
        self.class_label_6.setObjectName("class_label_6")
        self.name_teacher_edit = QtWidgets.QLineEdit(parent=self.widget_3)
        self.name_teacher_edit.setGeometry(QtCore.QRect(110, 70, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name_teacher_edit.setFont(font)
        self.name_teacher_edit.setStyleSheet("QLineEdit {     \n"
"    background: rgb(255, 230, 220);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.name_teacher_edit.setMaxLength(16)
        self.name_teacher_edit.setReadOnly(True)
        self.name_teacher_edit.setObjectName("name_teacher_edit")
        self.level_edit = QtWidgets.QLineEdit(parent=self.widget_3)
        self.level_edit.setGeometry(QtCore.QRect(110, 130, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.level_edit.setFont(font)
        self.level_edit.setStyleSheet("QLineEdit {     \n"
"    background: rgb(255, 230, 220);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.level_edit.setMaxLength(16)
        self.level_edit.setReadOnly(True)
        self.level_edit.setObjectName("level_edit")
        self.widget_4 = QtWidgets.QWidget(parent=self.teachers_page)
        self.widget_4.setGeometry(QtCore.QRect(140, 20, 501, 71))
        self.widget_4.setStyleSheet("QWidget { \n"
"    background:  rgb(255, 92, 71);\n"
"    border-radius: 20px;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.item_label_2 = QtWidgets.QLabel(parent=self.widget_4)
        self.item_label_2.setGeometry(QtCore.QRect(10, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.item_label_2.setFont(font)
        self.item_label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.item_label_2.setObjectName("item_label_2")
        self.item_edit = QtWidgets.QLineEdit(parent=self.widget_4)
        self.item_edit.setGeometry(QtCore.QRect(130, 20, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.item_edit.setFont(font)
        self.item_edit.setStyleSheet("QLineEdit {     \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.item_edit.setMaxLength(16)
        self.item_edit.setReadOnly(True)
        self.item_edit.setObjectName("item_edit")
        self.class_label_7 = QtWidgets.QLabel(parent=self.teachers_page)
        self.class_label_7.setGeometry(QtCore.QRect(10, 340, 751, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.class_label_7.setFont(font)
        self.class_label_7.setStyleSheet("color:rgb(156, 36, 0)")
        self.class_label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.class_label_7.setObjectName("class_label_7")
        self.teachers_comboBox = QtWidgets.QComboBox(parent=self.teachers_page)
        self.teachers_comboBox.setGeometry(QtCore.QRect(260, 390, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.teachers_comboBox.setFont(font)
        self.teachers_comboBox.setStyleSheet("QComboBox {    \n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 0px 6px;\n"
"     color:rgb(156, 36, 0); \n"
"}")
        self.teachers_comboBox.setObjectName("teachers_comboBox")
        self.teachers_comboBox.addItem("")
        self.teachers_comboBox.addItem("")
        self.teachers_comboBox.addItem("")
        self.teachers_comboBox.addItem("")
        self.teachers_comboBox.addItem("")
        self.teachers_comboBox.addItem("")
        self.teachers_comboBox.addItem("")
        self.change_btn = QtWidgets.QPushButton(parent=self.teachers_page)
        self.change_btn.setGeometry(QtCore.QRect(260, 440, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.change_btn.setFont(font)
        self.change_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.change_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color:  rgb(255, 92, 71);\n"
"    color:  rgb(255, 255, 255);\n"
"    font-size:  25px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 162, 125);\n"
"}")
        self.change_btn.setObjectName("change_btn")
        self.save_btn_2 = QtWidgets.QPushButton(parent=self.teachers_page)
        self.save_btn_2.setGeometry(QtCore.QRect(741, 510, 20, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.save_btn_2.setFont(font)
        self.save_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save_btn_2.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color:   rgb(255, 212, 194);\n"
"    color:   rgb(255, 212, 194);\n"
"    font-size:  25px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:   rgb(255, 212, 194);\n"
"}")
        self.save_btn_2.setObjectName("save_btn_2")
        self.stackedWidget.addWidget(self.teachers_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget_6 = QtWidgets.QWidget(parent=self.page)
        self.widget_6.setGeometry(QtCore.QRect(10, 60, 741, 151))
        self.widget_6.setStyleSheet("QWidget {\n"
"    border-radius: 8px;\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(156, 36, 0);\n"
"    font-size:  25px;\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.widget_6)
        self.textBrowser.setGeometry(QtCore.QRect(20, 10, 261, 131))
        self.textBrowser.setStyleSheet("QTextBrowser {\n"
"    border-radius: 8px;\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(156, 36, 0);\n"
"    font-size:  25px;\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.widget_6)
        self.checkBox_2.setGeometry(QtCore.QRect(710, 20, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setText("")
        self.checkBox_2.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label = QtWidgets.QLabel(parent=self.widget_6)
        self.label.setGeometry(QtCore.QRect(310, 10, 181, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("2024-06-14_193137.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.name_label_7 = QtWidgets.QLabel(parent=self.widget_6)
        self.name_label_7.setGeometry(QtCore.QRect(570, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.name_label_7.setFont(font)
        self.name_label_7.setStyleSheet("color:rgb(156, 36, 0)")
        self.name_label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.name_label_7.setObjectName("name_label_7")
        self.widget_7 = QtWidgets.QWidget(parent=self.page)
        self.widget_7.setGeometry(QtCore.QRect(10, 220, 741, 151))
        self.widget_7.setStyleSheet("QWidget {\n"
"    border-radius: 8px;\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(156, 36, 0);\n"
"    font-size:  25px;\n"
"}")
        self.widget_7.setObjectName("widget_7")
        self.textBrowser_3 = QtWidgets.QTextBrowser(parent=self.widget_7)
        self.textBrowser_3.setGeometry(QtCore.QRect(20, 10, 261, 131))
        self.textBrowser_3.setStyleSheet("QTextBrowser {\n"
"    border-radius: 8px;\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(156, 36, 0);\n"
"    font-size:  25px;\n"
"}")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self.widget_7)
        self.checkBox_4.setGeometry(QtCore.QRect(710, 20, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setText("")
        self.checkBox_4.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.name_label_8 = QtWidgets.QLabel(parent=self.widget_7)
        self.name_label_8.setGeometry(QtCore.QRect(570, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.name_label_8.setFont(font)
        self.name_label_8.setStyleSheet("color:rgb(156, 36, 0)")
        self.name_label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.name_label_8.setObjectName("name_label_8")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_2.setGeometry(QtCore.QRect(360, 30, 91, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("2024-06-14_201336.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.page)
        self.textBrowser_2.setGeometry(QtCore.QRect(100, 0, 561, 41))
        self.textBrowser_2.setStyleSheet("QTextBrowser {\n"
"    border-radius: 8px;\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(156, 36, 0);\n"
"    font-size:  25px;\n"
"}")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.widget_8 = QtWidgets.QWidget(parent=self.page)
        self.widget_8.setGeometry(QtCore.QRect(10, 380, 741, 151))
        self.widget_8.setStyleSheet("QWidget {\n"
"    border-radius: 8px;\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(156, 36, 0);\n"
"    font-size:  25px;\n"
"}")
        self.widget_8.setObjectName("widget_8")
        self.textBrowser_5 = QtWidgets.QTextBrowser(parent=self.widget_8)
        self.textBrowser_5.setGeometry(QtCore.QRect(20, 10, 261, 131))
        self.textBrowser_5.setStyleSheet("QTextBrowser {\n"
"    border-radius: 8px;\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color:  rgb(156, 36, 0);\n"
"    font-size:  25px;\n"
"}")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.checkBox_6 = QtWidgets.QCheckBox(parent=self.widget_8)
        self.checkBox_6.setGeometry(QtCore.QRect(710, 20, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setText("")
        self.checkBox_6.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.name_label_10 = QtWidgets.QLabel(parent=self.widget_8)
        self.name_label_10.setGeometry(QtCore.QRect(570, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.name_label_10.setFont(font)
        self.name_label_10.setStyleSheet("color:rgb(156, 36, 0)")
        self.name_label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.name_label_10.setObjectName("name_label_10")
        self.create_btn_3 = QtWidgets.QPushButton(parent=self.widget_8)
        self.create_btn_3.setGeometry(QtCore.QRect(520, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.create_btn_3.setFont(font)
        self.create_btn_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_btn_3.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color:  rgb(255, 92, 71);\n"
"    color:  rgb(255, 255, 255);\n"
"    font-size:  25px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 162, 125);\n"
"}")
        self.create_btn_3.setObjectName("create_btn_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_8)
        self.label_4.setGeometry(QtCore.QRect(340, 10, 131, 121))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("2024-06-14_201935.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page)
        MainWindowStudent.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowStudent)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindowStudent)

    def retranslateUi(self, MainWindowStudent):
        _translate = QtCore.QCoreApplication.translate
        MainWindowStudent.setWindowTitle(_translate("MainWindowStudent", "Онлайн школа Бебрика - Главное меню"))
        self.my_account_btn.setText(_translate("MainWindowStudent", "Мой аккаунт"))
        self.schedule_btn.setText(_translate("MainWindowStudent", "Расписание"))
        self.teachers_btn.setText(_translate("MainWindowStudent", "Преподаватели"))
        self.lesson_btn.setText(_translate("MainWindowStudent", "Пора на урок"))
        self.exit_btn.setText(_translate("MainWindowStudent", "Выйти"))
        self.name_label.setText(_translate("MainWindowStudent", "Имя: "))
        self.surname_label.setText(_translate("MainWindowStudent", "Фамилия: "))
        self.class_label.setText(_translate("MainWindowStudent", "Класс: "))
        self.item_comboBox.setItemText(0, _translate("MainWindowStudent", "Не выбран"))
        self.item_comboBox.setItemText(1, _translate("MainWindowStudent", "Математика"))
        self.item_comboBox.setItemText(2, _translate("MainWindowStudent", "Русский язык"))
        self.item_comboBox.setItemText(3, _translate("MainWindowStudent", "Английский язык"))
        self.item_comboBox.setItemText(4, _translate("MainWindowStudent", "Химия"))
        self.item_comboBox.setItemText(5, _translate("MainWindowStudent", "Физика"))
        self.item_comboBox.setItemText(6, _translate("MainWindowStudent", "Информатика"))
        self.item_label.setText(_translate("MainWindowStudent", "Предмет: "))
        self.redpass_label.setText(_translate("MainWindowStudent", "Изменение пароля:"))
        self.oldpass_label.setText(_translate("MainWindowStudent", "Старый пароль: "))
        self.newpass_label.setText(_translate("MainWindowStudent", "Новый пароль: "))
        self.create_btn.setText(_translate("MainWindowStudent", "Редактировать"))
        self.save_btn.setText(_translate("MainWindowStudent", "Сохранить"))
        self.thu_label.setText(_translate("MainWindowStudent", "Четверг"))
        self.update_btn.setText(_translate("MainWindowStudent", "Обновить"))
        self.sun_label.setText(_translate("MainWindowStudent", "Воскресенье"))
        self.tue_label.setText(_translate("MainWindowStudent", "Вторник"))
        self.fri_label.setText(_translate("MainWindowStudent", "Пятница"))
        self.mon_label.setText(_translate("MainWindowStudent", "Понедельник"))
        self.sat_label.setText(_translate("MainWindowStudent", "Суббота"))
        self.wed_label.setText(_translate("MainWindowStudent", "Среда"))
        self.class_label_4.setText(_translate("MainWindowStudent", "Ваш преподаватель:"))
        self.class_label_5.setText(_translate("MainWindowStudent", "Имя:"))
        self.class_label_6.setText(_translate("MainWindowStudent", "Стаж:"))
        self.item_label_2.setText(_translate("MainWindowStudent", "Предмет: "))
        self.class_label_7.setText(_translate("MainWindowStudent", "Выбор нового преподователя:"))
        self.teachers_comboBox.setItemText(0, _translate("MainWindowStudent", "Не выбран"))
        self.teachers_comboBox.setItemText(1, _translate("MainWindowStudent", "Егор Бобрунов"))
        self.teachers_comboBox.setItemText(2, _translate("MainWindowStudent", "Олег Диких"))
        self.teachers_comboBox.setItemText(3, _translate("MainWindowStudent", "Степан Руденко"))
        self.teachers_comboBox.setItemText(4, _translate("MainWindowStudent", "Светлана Березина"))
        self.teachers_comboBox.setItemText(5, _translate("MainWindowStudent", "Кирилл Мазур"))
        self.teachers_comboBox.setItemText(6, _translate("MainWindowStudent", "Андрей Бебур"))
        self.change_btn.setText(_translate("MainWindowStudent", "Сменить"))
        self.save_btn_2.setText(_translate("MainWindowStudent", "Сохранить"))
        self.textBrowser.setHtml(_translate("MainWindowStudent", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:25px; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Качество видео, свет, задний фон и внешний вид</span></p></body></html>"))
        self.name_label_7.setText(_translate("MainWindowStudent", "Проверено"))
        self.textBrowser_3.setHtml(_translate("MainWindowStudent", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:25px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:25px;\">Качество микрофона и отсутствие шума на заднем плане</span></p></body></html>"))
        self.name_label_8.setText(_translate("MainWindowStudent", "Проверено"))
        self.textBrowser_2.setHtml(_translate("MainWindowStudent", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:25px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Перед подключением на урок проверьте:</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("MainWindowStudent", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:25px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:25px;\">Скорость интернета не менее 6 Мбит/сек</span></p></body></html>"))
        self.name_label_10.setText(_translate("MainWindowStudent", "Проверено"))
        self.create_btn_3.setText(_translate("MainWindowStudent", "Подключится"))
